services:
  pokedex-tcg:
    image: ghcr.io/juanjose1245-maker/pokedextcg:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment: []
      # - ADMIN_PASSWORD=opcional-si-preferís-fijarla-por-variable-de-entorno
    volumes:
      - ./data:/app/data
